apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: characters-deployment
spec:
  selector:
    matchLabels:
      app: characters
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: characters
    spec:
      containers:
      - name: characters
        image: <your character image URL goes here>
        ports:
        - containerPort: 8081
